# Generated by Django 3.1.7 on 2021-03-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_info',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
    ]
