# Generated by Django 3.1.7 on 2021-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_match_match_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('KR', 'Korea'), ('CN', 'China'), ('INT', 'International')], default='oop', max_length=3),
            preserve_default=False,
        ),
    ]
