# Generated by Django 3.1.7 on 2021-03-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_match_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_info',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_t1_win_prob',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teamrating',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
