# Generated by Django 3.1.7 on 2021-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20210318_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_processed',
            field=models.BooleanField(default=False),
        ),
    ]
