# Generated by Django 3.1.7 on 2021-04-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_match_best_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_datetime',
            new_name='start_timestamp',
        ),
    ]
