# Generated by Django 3.1.7 on 2021-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20210403_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
