# Generated by Django 3.1.7 on 2021-07-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ratings', '0011_teamratinghistory'), ('ratings', '0012_remove_teamratinghistory_match'), ('ratings', '0013_teamratinghistory_match')]

    dependencies = [
        ('ratings', '0010_auto_20210426_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRatingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.team')),
                ('match', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ratings.match')),
            ],
        ),
    ]
