# Generated by Django 3.1.7 on 2021-07-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_auto_20210722_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamratinghistory',
            name='rating_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
