# Generated by Django 3.1.7 on 2023-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_remove_teamratinghistory_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_info',
            field=models.CharField(max_length=50),
        ),
    ]
